version: '3'

services:
  app:
    image: golang
    container_name: gointensivo
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
    working_dir: /go/src/app
    command: tail -f /dev/null
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    volumes:
      - ./.docker/mysql:/var/lib/mysql

    